steps:
# Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/hello-alton:$COMMIT_SHA', '.']


# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/hello-alton:$COMMIT_SHA']


- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/hellodeployment', 'hellonode=gcr.io/robust-flow-387911/hello-alton:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'
